### ISSUE TITLE
[BLOG ISSUE] - Monitoring Media Varken

### ISSUE THREAD

**Issue by cvc90** [alexandzors/blog-files#1]
Hi, and tried to follow the guide [Monitoring Media Varken](https://blog.alexsguardian.net/posts/2022/12/04/MonitoringMediaVarken/) to make Varken work with InfluxDB v2, but I haven't been able to because it finds an error in step "git fetch origin pull/242/head/develop:varken-influxdb2" cannot find the path

![image](https://user-images.githubusercontent.com/76731844/216958613-b9d9b69e-c57f-4035-b944-e654521ea44d.png)
![image](https://user-images.githubusercontent.com/76731844/217500792-4cecae30-ac0a-4231-a121-d9a5da759a1c.png)

I also tried to create a Docker directly from the [Varken - influxdb-flux-dashboard](https://github.com/alexandzors/Varken/tree/influxdb-flux-dashboard) repository, trying URLs 1: github.com/alexandzors /varken:influxdb-flux-dashboard and URL 2: ghcr.io/alexandzors/varken:influxdb-flux-dashboard but it doesn't seem to be in public mode, because it denies me access.
 
Could you help me find a solution to these problems?

**Comment by alexandzors** [comment]
Hey! For that first issue. Can you send me a directory listing of what the step before created? The step before:

```
cd /opt/docker/varken/.git
git clone https://github.com/Boerderij/Varken.git
```

As for the docker image I do not host my own version so that would be why those urls do not work. That repository exists only so I am able to submit PRs to the original repository.

**Comment by cvc90** [comment]
I leave you a screenshot of the list of files

![image](https://user-images.githubusercontent.com/76731844/217500219-c174ecd9-db5a-49e3-aa6c-5187fce8d2a0.png)

Would it be too much to ask to host a final version for Docker? Just ready to go?

**Comment by alexandzors** [comment]
So I made a typo in the command for fetching the PR. It should be: 

```
git fetch origin pull/242/head:varken-influxdb2
```

Which will give you an output as follows:

```shell
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 21 (delta 16), reused 21 (delta 16), pack-reused 0
Unpacking objects: 100% (21/21), 2.65 KiB | 679.00 KiB/s, done.
From https://github.com/Boerderij/Varken
 * [new ref]         refs/pull/242/head -> varken-influxdb2
```

I will update the post on the blog with the corrected command. As for your other question, no I will not be hosting an image of Varken. This is a temporary workaround for influx v2 support until the PR gets merged on the main Varken repository. As such I'd rather focus my efforts on helping the Varken dev team instead of spinning up my own copy.

Thanks for bringing the issue to my attention and let me know if you encounter any other issues!

**Comment by alexandzors** [comment]
Blog post has been fixed.

Note: The site cache may take a bit to update to reflect the changes.

**Comment by cvc90** [comment]
Thank you!, I was able to follow the guide until the end.

I already have Varken running with InfluxDB V2 and the Grafana panel already displays its data correctly.

There is another error in the guide in the "Setting up the Docker Compose file" section, as you can see in the image the repo it points to is yourname/varken:influxdb-dev and it should be yourname/varken:influxdb2-dev

![image](https://user-images.githubusercontent.com/76731844/218048499-8ac2c93d-2711-48de-a675-3ee9a0f58d61.png)

**Comment by alexandzors** [comment]
Awesome, glad you were able to follow the post! As for the typo I will fix that on the next update cycle for the blog. Appreciate the heads up!
